# Generated by Django 4.2.11 on 2026-05-29 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WarningRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='规则名称')),
                ('metric', models.CharField(choices=[('pressure', '压力'), ('flow', '流量')], max_length=50, verbose_name='监测指标')),
                ('condition', models.CharField(choices=[('lt', '小于'), ('gt', '大于'), ('lte', '小于等于'), ('gte', '大于等于')], max_length=20, verbose_name='条件')),
                ('threshold', models.FloatField(verbose_name='阈值')),
                ('consecutive_points', models.IntegerField(default=3, verbose_name='连续点数')),
                ('enabled', models.BooleanField(default=True, verbose_name='是否启用')),
                ('severity', models.CharField(choices=[('low', '低'), ('medium', '中'), ('high', '高')], default='medium', max_length=20, verbose_name='严重程度')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '预警规则',
                'verbose_name_plural': '预警规则',
                'db_table': 'warning_rule',
            },
        ),
    ]
