# Generated by Django 4.2.11 on 2026-05-29 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ZoneStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone', models.CharField(max_length=100, verbose_name='分区')),
                ('stat_date', models.DateField(verbose_name='统计日期')),
                ('avg_pressure', models.FloatField(default=0, verbose_name='平均压力(MPa)')),
                ('min_pressure', models.FloatField(default=0, verbose_name='最低压力(MPa)')),
                ('max_pressure', models.FloatField(default=0, verbose_name='最高压力(MPa)')),
                ('avg_flow', models.FloatField(default=0, verbose_name='平均流量(m³/h)')),
                ('total_flow', models.FloatField(default=0, verbose_name='总流量(m³)')),
                ('pressure_compliance', models.FloatField(default=0, verbose_name='压力达标率(%)')),
                ('flow_compliance', models.FloatField(default=0, verbose_name='流量达标率(%)')),
                ('fault_count', models.IntegerField(default=0, verbose_name='故障次数')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '分区统计',
                'verbose_name_plural': '分区统计',
                'db_table': 'zone_statistics',
                'unique_together': {('zone', 'stat_date')},
            },
        ),
    ]
