# Generated by Django 4.2.7 on 2026-05-29 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancereport',
            name='fault_rate',
            field=models.FloatField(default=0, verbose_name='故障率(%)'),
        ),
        migrations.AddField(
            model_name='maintenancereport',
            name='online_rate',
            field=models.FloatField(default=0, verbose_name='在线率(%)'),
        ),
        migrations.AddField(
            model_name='maintenancereport',
            name='report_notes',
            field=models.TextField(blank=True, verbose_name='报表备注'),
        ),
        migrations.AddField(
            model_name='maintenancereport',
            name='resolution_rate',
            field=models.FloatField(default=0, verbose_name='解决率(%)'),
        ),
    ]
