FROM maven:3.8.6-jdk-8 AS builder
WORKDIR /app

COPY pom.xml .
COPY common ./common
COPY protocol-parser ./protocol-parser

RUN mvn clean install -pl common -am -DskipTests
RUN mvn clean package -pl protocol-parser -am -DskipTests

FROM openjdk:8-jre-alpine
WORKDIR /app
COPY --from=builder /app/protocol-parser/target/protocol-parser-1.0.0.jar /app/app.jar

EXPOSE 8081

ENV JAVA_OPTS="-Xms256m -Xmx512m -XX:+UseG1GC"

ENTRYPOINT ["sh", "-c", "java $JAVA_OPTS -jar /app/app.jar"]
