# Generated by Django 4.2.11 on 2026-05-29 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataQualityReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_date', models.DateField(verbose_name='报告日期')),
                ('zone', models.CharField(blank=True, max_length=100, verbose_name='分区')),
                ('overall_score', models.FloatField(verbose_name='总体质量评分')),
                ('pressure_score', models.FloatField(verbose_name='压力数据质量评分')),
                ('flow_score', models.FloatField(verbose_name='流量数据质量评分')),
                ('total_records', models.IntegerField(verbose_name='总记录数')),
                ('cleaned_records', models.IntegerField(verbose_name='清洗记录数')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '数据质量报告',
                'verbose_name_plural': '数据质量报告',
                'db_table': 'data_quality_report',
                'unique_together': {('report_date', 'zone')},
            },
        ),
    ]
