server:
  port: 8081

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: ventilation_system
      uri: mongodb://localhost:27017/ventilation_system

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    serialization:
      write-dates-as-timestamps: false
